### ISSUE TITLE
Conda fails to install OpenAstronomy Packages

### ISSUE THREAD

**Issue by ruarimac** [OpenAstronomy/conda-channel#31]
Hi,
I've used OpenAstronomy in the past and I've never had issues but while setting up a new machine I've been unable to install healpy via OpenAstronomy using Conda. The error message is below:

`    healpy: 1.9.1-np111py27_0 openastronomy

Proceed ([y]/n)? y

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /home/ruari/anaconda2  (writable)
    default environment : /home/ruari/anaconda2
       envs directories : /home/ruari/anaconda2/envs
                          /home/ruari/.conda/envs
          package cache : /home/ruari/anaconda2/pkgs
                          /home/ruari/.conda/pkgs
           channel URLs : https://conda.anaconda.org/openastronomy/linux-64
                          https://conda.anaconda.org/openastronomy/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/ruari/.condarc
           offline mode : False
             user-agent : conda/4.3.13 requests/2.12.4 CPython/2.7.13 Linux/4.4.0-31-generic debian/stretch/sid glibc/2.23
                UID:GID : 1000:1000

`$ /home/ruari/anaconda2/bin/conda install -c openastronomy healpy`

    Traceback (most recent call last):
      File "/home/ruari/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/ruari/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/home/ruari/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/ruari/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/ruari/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 823, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/ruari/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/home/ruari/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 100, in PROGRESSIVEFETCHEXTRACT_CMD
        progressive_fetch_extract.execute()
      File "/home/ruari/anaconda2/lib/python2.7/site-packages/conda/core/package_cache.py", line 474, in execute
        self._execute_action(action)
      File "/home/ruari/anaconda2/lib/python2.7/site-packages/conda/core/package_cache.py", line 490, in _execute_action
        exceptions.append(CondaError(repr(e)))
      File "/home/ruari/anaconda2/lib/python2.7/site-packages/conda/__init__.py", line 43, in __repr__
        return '%s: %s\n' % (self.__class__.__name__, text_type(self))
      File "/home/ruari/anaconda2/lib/python2.7/site-packages/conda/__init__.py", line 46, in __str__
        return text_type(self.message % self._kwargs)
    TypeError: not enough arguments for format string
`

I tried a few other OpenAstronomy packages (cfitsio, aplpy) which I've used in the past and I get the same error. I don't think it's a Conda issue as it installs other packages. I also can't install healpy manually or with pip as I get an error like this:

https://github.com/healpy/healpy/issues/367

AplPy on the other hand did install with pip but I really need healpy. Any help would be greatly appreciated, sorry if this is a dumb mistake.

Ruari

**Comment by mwcraig** [comment]
There are apparently some issues right now with Amazon S3...one of their server banks is down or something. Can you please try again in a few hours and let us know if it works then?

**Comment by ruarimac** [comment]
Just tried it this morning as suggested and it seems to be working now. Thanks mwcraig.

**Comment by mwcraig** [comment]
no problem! Glad it wasn't anything I had to fix :grinning:
